export const amenities = [
  "Desk",
  "Wardrobe",
  "Bathroom with shower",
  "Bathroom with bathtub",
  "Hairdryer",
  "Bathrobes",
  "Slippers",
  "Kitchenette",
  "Individual controlled AC units",
  "Nespresso coffee machine",
  "Eco stove/oven",
  "Fridge/freezer",
  "49'' LED/LCD flat screen TV",
  "High speed Wi-Fi",
  "DSTV Hotel Bouquet",
  "Microwave/dishwasher",
  "Washer/dryer",
  "Ensuite-bathroom",
  "Private balcony/dining area",
  "Keyless electronic unit entry",
];
